// Caption ideas for templates and pictures that have no captions of their own.
// Each template gets a different, stable selection: themed ideas first when its name
// matches a theme's words, then general ideas for its number of text boxes.
window.MEME_IDEAS = {
  themes: {
    animals: {
      words: ['cat', 'dog', 'doge', 'cheems', 'kitten', 'puppy', 'bird', 'seagull', 'pigeon', 'monkey', 'frog', 'kermit', 'raptor', 'owl', 'bear', 'shiba', 'animal', 'goat', 'duck', 'horse', 'fish'],
      ideas: [
        ['My cat at 3am', 'deciding it is time to run laps'],
        ['When you say "walk"', 'just to check something'],
        ['My dog when I come home', 'after being gone for 5 minutes'],
        ['When the vet says', 'it is time for the injection'],
        ['Me watching my pet', 'knock my glass off the table'],
        ['When the food bowl', 'is only half full'],
        ['My cat ignoring the expensive bed', 'and sleeping in the box it came in'],
        ['When you open a snack', 'and every animal in the house appears'],
      ],
    },
    sad: {
      words: ['sad', 'cry', 'crying', 'tears', 'pain', 'lonely', 'depressed', 'keanu', 'affleck', 'pablo', 'waiting'],
      ideas: [
        ['When the weekend', 'is over before it started'],
        ['Me checking my bank account', 'after one fun weekend'],
        ['When you finally find the remote', 'and the battery is dead'],
        ['When your food arrives', 'and it is the wrong order'],
        ['Me after the holidays', 'looking at my alarm clock'],
        ['When you remember', 'something embarrassing from 10 years ago'],
        ['When you are ready to sleep', 'and your brain starts a podcast'],
        ['When the group chat goes silent', 'right after your message'],
      ],
    },
    angry: {
      words: ['angry', 'mad', 'yelling', 'scream', 'screaming', 'rage', 'fist', 'slap', 'slapping', 'furious', 'annoyed', 'grumpy'],
      ideas: [
        ['When someone says', '"just relax" while you are angry'],
        ['Me when the wifi drops', 'in the last minute of the game'],
        ['When someone eats', 'the food I labelled with my name'],
        ['Me when people walk slowly', 'in a narrow hallway'],
        ['When the printer says', 'paper jam with no paper in it'],
        ['When someone replies', '"k" to a long message'],
        ['Me when the delivery says delivered', 'and it is not here'],
        ['When the tech guy asks', 'have you tried turning it off and on'],
      ],
    },
    shocked: {
      words: ['surprised', 'shocked', 'shock', 'pikachu', 'wat', 'what', 'confused', 'unsettled', 'scared', 'afraid', 'wtf', 'omg'],
      ideas: [
        ['Me after doing nothing all day', 'when the day is already over'],
        ['When the teacher says', 'the test is today, not tomorrow'],
        ['When someone says', 'they have never seen a single meme'],
        ['When you check your screen time', 'for the first time this week'],
        ['When the code works', 'on the first try'],
        ['Me seeing the electricity bill', 'after one week of heater use'],
        ['When the "quick question"', 'turns into a 2 hour meeting'],
        ['When the price', 'did not include tax'],
      ],
    },
    thinking: {
      words: ['thinking', 'think', 'brain', 'smart', 'philosoraptor', 'genius', 'wonder', 'idea', 'plan', 'morpheus', 'mind', 'conspiracy'],
      ideas: [
        ['If I sleep now', 'I can be tired in the morning too'],
        ['If you never check your bank account', 'you are never broke'],
        ['Why do they call it a building', 'if it is already built'],
        ['If I start my diet tomorrow', 'today is the last chance for cake'],
        ['If nobody saw me do it', 'did it really happen'],
        ['If I do not open the email', 'the problem does not exist'],
        ['Taking a nap', 'to save energy for my next nap'],
        ['If it is on sale', 'buying it is basically saving money'],
      ],
    },
    happy: {
      words: ['success', 'happy', 'win', 'winning', 'cheers', 'celebrate', 'laughing', 'laugh', 'party', 'dance', 'yes', 'victory', 'good'],
      ideas: [
        ['When you find money', 'in your old jacket'],
        ['When the meeting', 'gets cancelled'],
        ['When your food arrives', 'earlier than expected'],
        ['When you wake up', 'and it is still 3 more hours until the alarm'],
        ['When the teacher says', 'no homework this weekend'],
        ['When your phone hits 100%', 'right when you need to leave'],
        ['When the bug', 'fixes itself'],
        ['When the friend who never pays', 'pays for everyone'],
      ],
    },
    work: {
      words: ['office', 'boss', 'meeting', 'boardroom', 'work', 'job', 'business', 'corporate', 'presentation', 'salesman', 'trade', 'deal', 'interview'],
      ideas: [
        ['When the boss says', 'we are like a family here'],
        ['Me on a Zoom call', 'pretending my camera is broken'],
        ['When the meeting', 'could have been an email'],
        ['When someone says', '"as per my last email"'],
        ['Me at 4:59pm', 'when the boss says "quick task"'],
        ['When it is Friday', 'and someone schedules a meeting at 4:30'],
        ['When the client says', 'small change, should be quick'],
        ['Me pretending to work', 'when the manager walks past'],
      ],
    },
    school: {
      words: ['school', 'student', 'teacher', 'class', 'exam', 'test', 'homework', 'study', 'college', 'university', 'kid', 'nerd'],
      ideas: [
        ['When the teacher says', 'find a partner'],
        ['Me in an exam', 'after studying the wrong chapter'],
        ['When you finish the homework', 'and realise it was due yesterday'],
        ['When the group project', 'is graded on your part only'],
        ['When the teacher says', 'this will not be on the test'],
        ['Me before the exam', 'trying to learn a whole term in one night'],
        ['When class ends early', 'by 5 minutes'],
        ['When you raise your hand', 'and forget the question'],
      ],
    },
    food: {
      words: ['food', 'eat', 'eating', 'pizza', 'burger', 'chef', 'cook', 'hungry', 'sandwich', 'snack', 'coffee', 'tea', 'cheese', 'krabs'],
      ideas: [
        ['Me saying I will eat healthy', 'also me ordering a large pizza'],
        ['When mom says', 'we have food at home'],
        ['Me opening the fridge', 'for the 7th time in an hour'],
        ['When someone asks for a bite', 'and takes half'],
        ['Me before my morning coffee', 'versus after'],
        ['When the waiter brings', 'someone else\'s food first'],
        ['Me pretending to be full', 'until dessert arrives'],
        ['When the recipe says', '"cook for 5 minutes"'],
      ],
    },
  },

  // Two text boxes, usually top and bottom.
  two: [
    ['Me: I will sleep early tonight', 'Also me at 3am:'],
    ['When the code works', 'and you do not know why'],
    ['Nobody:', 'Absolutely nobody:'],
    ['Me after one productive hour', 'time for a 3 hour break'],
    ['When someone says', 'it will only take 5 minutes'],
    ['When the wifi', 'disconnects for one second'],
    ['Me pretending to listen', 'thinking about food'],
    ['Me seeing my bank account', 'after the weekend'],
    ['When you finally', 'find the TV remote'],
    ['When you hear your name', 'in a conversation you are not part of'],
    ['Me when someone says', 'they will be there in 5 minutes'],
    ['When you say "you too"', 'to the waiter who said "enjoy your meal"'],
    ['When you wave back', 'at someone who was waving at the person behind you'],
    ['Me at the start of the year', 'versus me in March'],
    ['When you laugh at a joke', 'and then have to explain it'],
    ['When you are the last one', 'to understand the joke'],
    ['Me telling myself', 'just 5 more minutes'],
    ['When your phone is at 1%', 'and the charger is across the room'],
    ['Me trying to act normal', 'after tripping in public'],
    ['When the elevator door', 'is about to close and you run'],
    ['When you open 50 tabs', 'to read later'],
    ['Me reading the terms and conditions', 'by clicking "I agree"'],
    ['When you pretend to text', 'to avoid someone you know'],
    ['When someone spoils', 'the ending of the show'],
    ['Me waiting for my turn', 'to say "same"'],
    ['When the song you skip', 'plays 4 times in a row'],
    ['When you send a message', 'and immediately see the typo'],
    ['When the alarm rings', 'right in the best part of the dream'],
    ['Me looking for my glasses', 'while wearing them'],
    ['When the parking spot', 'is just a little too small'],
    ['When you clean your room', 'and find everything you lost last year'],
    ['When you say goodbye', 'and walk the same way'],
    ['Me at a party', 'looking for the host\'s dog'],
    ['When the package says', 'arriving between 8am and 8pm'],
    ['When someone asks', 'what you did all weekend'],
    ['When the update', 'restarts your computer without asking'],
    ['Me checking the fridge', 'hoping new food appeared'],
    ['When the video buffers', 'right at the best moment'],
    ['When you try to act cool', 'and the door says pull'],
    ['When you remember', 'you left the stove on'],
  ],

  // One text box.
  one: [
    ['Me pretending everything is fine'],
    ['When the weekend finally arrives'],
    ['That feeling when the code works'],
    ['Me on Monday morning'],
    ['When someone says "we need to talk"'],
    ['Me explaining memes to my parents'],
    ['When the food arrives'],
    ['Me after one cup of coffee'],
    ['When the Wi-Fi comes back'],
    ['Nobody asked, but here we are'],
    ['Me trying to be productive'],
    ['When you hear the ice cream truck'],
    ['My last brain cell during the exam'],
    ['When the plan actually works'],
    ['Me avoiding responsibilities'],
  ],

  // Three text boxes: set-up, twist, punchline.
  three: [
    ['Me', 'Going to bed early', 'Watching videos until 3am'],
    ['My plans', 'My motivation', 'My bed'],
    ['Me', 'My diet', 'One slice of cake'],
    ['Monday me', 'Wednesday me', 'Friday me'],
    ['What I ordered', 'What I expected', 'What I got'],
    ['Me', 'Saving money', 'A sale sign'],
    ['Students', 'Studying all term', 'The night before the exam'],
    ['Me', 'Reading the instructions', 'Breaking it first'],
    ['How it started', 'How it is going', 'How it ended'],
    ['Me', 'My responsibilities', 'A nap'],
    ['Plan A', 'Plan B', 'Panic'],
    ['Me', 'Being productive', 'One notification'],
    ['The bug', 'The fix', 'Two new bugs'],
    ['Me', 'Going to the gym', 'Staying on the couch'],
    ['Expectation', 'Reality', 'Me pretending it is fine'],
  ],

  // Four or more text boxes.
  four: [
    ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
    ['Planning', 'Starting', 'Struggling', 'Giving up'],
    ['Waking up', 'Coffee', 'More coffee', 'Still tired'],
    ['Day 1 of the diet', 'Day 2', 'Day 3', 'Pizza'],
    ['Idea', 'Excitement', 'Reality', 'New idea'],
    ['Me at 9am', 'Me at noon', 'Me at 3pm', 'Me at 5pm'],
    ['January me', 'March me', 'June me', 'December me'],
    ['Study', 'Snack', 'Scroll', 'Panic'],
    ['Payday', 'Shopping', 'Bills', 'Broke'],
    ['Alarm', 'Snooze', 'Snooze again', 'Late'],
  ],
};
